name: "Test VPN"
on:
  push:
    branches: main

jobs:
  test-VPN:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get --yes install --no-install-recommends openvpn
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: chmod connext.sh
        run: chmod +x ./vpn/connect.sh

      - name: Connect to ProtonVPN
        run: vpn/connect.sh vpn/config.ovpn
        env:
          VPN_USERNAME: ${{ secrets.PROTONVPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.PROTONVPN_PASSWORD }}
          VPN_ROOT_CERT: ${{ secrets.PROTONVPN_ROOT_CERT }}
          VPN_TLS_AUTH_KEY: ${{ secrets.PROTONVPN_TLS_AUTH_KEY }}

      - name: Render rmd
        run: Rscript -e 'print("coucou !!")'

      - name: Disconnect from ProtonVPN
        run: sudo killall openvpn
        if: ${{ always() }}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.html
          git commit -m 'test GH actions' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
